### ISSUE TITLE
How to I get my PNG into a sprite info file 

### ISSUE THREAD

**Issue by Dmartin42** [CalvinMT/LITIengine_test#2]
How did you do this?

**Comment by CalvinMT** [comment]
You need to create your sprites which can be PNGs.
I made mine with a free softawre called paint.net.

Each one of your PNGs contains a row of sprites of same sizes which makes one of the animations of your character.
Have look around the sprites folder on the LITIengine's Github.

The sprites.info file (btw, can be called otherwise but need to end with .info) is a file that you need to create.
You can edit it with a simple notepad or use, as I recommend, notepad++.

**Comment by Dmartin42** [comment]
![papaellisimg](https://user-images.githubusercontent.com/45320702/49396599-3456d780-f6ff-11e8-99bd-32545fa2fb69.png)
Is this my Sprite? Or do I need to "cut up" the photo into individual characters? 


Like this? or the one above??
![tile005](https://user-images.githubusercontent.com/45320702/49396723-7718af80-f6ff-11e8-858e-235c903fa28d.png)
![tile006](https://user-images.githubusercontent.com/45320702/49396724-7718af80-f6ff-11e8-9944-54732c846071.png)
![tile007](https://user-images.githubusercontent.com/45320702/49396725-7718af80-f6ff-11e8-859d-c8e4ac1ce0f7.png)
![tile008](https://user-images.githubusercontent.com/45320702/49396726-7718af80-f6ff-11e8-8b1f-513cfe34d38c.png)
![tile009](https://user-images.githubusercontent.com/45320702/49396727-77b14600-f6ff-11e8-99a1-d439f3a2426a.png)
![tile010](https://user-images.githubusercontent.com/45320702/49396728-77b14600-f6ff-11e8-94c4-2a4649f73d99.png)
![tile011](https://user-images.githubusercontent.com/45320702/49396729-77b14600-f6ff-11e8-8e6d-b8f46c70a64e.png)
![tile000](https://user-images.githubusercontent.com/45320702/49396730-77b14600-f6ff-11e8-85f3-65ee5b9a569d.png)
![tile001](https://user-images.githubusercontent.com/45320702/49396732-7849dc80-f6ff-11e8-9366-075e52d2c5f3.png)
![tile002](https://user-images.githubusercontent.com/45320702/49396733-7849dc80-f6ff-11e8-8e70-782a8faf029b.png)
![tile003](https://user-images.githubusercontent.com/45320702/49396734-7849dc80-f6ff-11e8-9e7e-6bdc179a48e3.png)
![tile004](https://user-images.githubusercontent.com/45320702/49396735-7849dc80-f6ff-11e8-89bc-072f3d783bff.png)

**Comment by CalvinMT** [comment]
No.
You only need to cut the rows.
